apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
  - image: userbit/kubia:v2-8081
    name: kubia2
    ports:
    - containerPort: 8081
      protocol: TCP
  - image: userbit/kubia:v1
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
